<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategoryTable extends Doctrine_Table
{   
    public function getWithJobs()
    {
        $q = $this->createQuery('c')
        ->leftJoin('c.JobeetJobs j')
        ->andWhere('j.is_activated = ?', 1);
 
        return $q->execute();
    }

}